# MPLAB IDE generated this makefile for use with GNU make.
# Project: chenillard.mcp
# Date: Mon Oct 17 18:26:46 2011

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

chenillard.cof : chenillard.o
	$(LD) /p18F87J11 "chenillard.o" /u_CRUNTIME /z__MPLAB_BUILD=1 /o"chenillard.cof" /M"chenillard.map" /W

chenillard.o : chenillard.c ../../../../../Program\ Files\ (x86)/Microchip/mplabc18/v3.40/h/p18f87j11.h
	$(CC) -p=18F87J11 "chenillard.c" -fo="chenillard.o" -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "chenillard.o" "chenillard.cof" "chenillard.hex"

